<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="QA-Imran" ignored="0" name="RestAssured Test" tests="13" failures="4" timestamp="05 Jun 2018 11:15:20 GMT" time="18.607" errors="0">
  <testcase name="TC_001_Passing0InPath" time="5.587" classname="com.icreon.customer.customerProfileInformationTest">
    <failure type="java.lang.AssertionError" message="expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [404] but found [200]
at com.icreon.customer.customerProfileInformationTest.TC_001_Passing0InPath(customerProfileInformationTest.java:71)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TC_001_Passing0InPath -->
  <testcase name="TC_002_PassingProfileIDinPath" time="0.52" classname="com.icreon.customer.customerProfileInformationTest">
    <failure type="java.lang.AssertionError" message="expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [404] but found [200]
at com.icreon.customer.customerProfileInformationTest.TC_002_PassingProfileIDinPath(customerProfileInformationTest.java:91)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TC_002_PassingProfileIDinPath -->
  <testcase name="TC_003_PassingWrongProfileIDinPath" time="0.496" classname="com.icreon.customer.customerProfileInformationTest"/>
  <testcase name="TC_004_requestWithoutAuthorization" time="0.585" classname="com.icreon.customer.customerProfileInformationTest"/>
  <testcase name="TC_005_requestWithoutX_Fred_Auth" time="0.466" classname="com.icreon.customer.customerProfileInformationTest"/>
  <testcase name="TC_006_requestWithoutCustomerId" time="0.466" classname="com.icreon.customer.customerProfileInformationTest"/>
  <testcase name="TC_007_mismatchedCustomerId" time="0.469" classname="com.icreon.customer.customerProfileInformationTest"/>
  <testcase name="custProfileInfo" time="0.636" classname="com.icreon.customer.customerProfileInformationTest"/>
  <testcase name="TC_001_SavingANewKid" time="1.461" classname="com.icreon.customer.kidTest">
    <failure type="java.lang.AssertionError" message="expected [Success] but found [Record already exist]">
      <![CDATA[java.lang.AssertionError: expected [Success] but found [Record already exist]
at com.icreon.customer.kidTest.TC_001_SavingANewKid(kidTest.java:63)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TC_001_SavingANewKid -->
  <testcase name="TC_001_MileageNumberAlreadyExist" time="3.121" classname="com.icreon.customer.MileagePlusRewardNumberTest"/>
  <testcase name="TC_002_MileageNumberNotValid" time="0.489" classname="com.icreon.customer.MileagePlusRewardNumberTest"/>
  <testcase name="TC_001_PassingAllParametersCorrectly" time="0.892" classname="com.icreon.customer.stravaUpdateTest"/>
  <testcase name="TC_002_UsingExsitingStravaId" time="0.877" classname="com.icreon.customer.stravaUpdateTest">
    <failure type="java.lang.AssertionError" message="expected [Success] but found [Starva Id already exist]">
      <![CDATA[java.lang.AssertionError: expected [Success] but found [Starva Id already exist]
at com.icreon.customer.stravaUpdateTest.TC_002_UsingExsitingStravaId(stravaUpdateTest.java:80)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TC_002_UsingExsitingStravaId -->
</testsuite> <!-- RestAssured Test -->
